broker1/broker1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # XXX this is spitting out not unique warning
    path('', include('inputs.urls')),
    path('inputs/', include('inputs.urls')),
    path('admin/', admin.site.urls),
]

broker1/inputs/urls.py
# -*- coding: utf-8 -*-
"""
Created on Sat Jun 23 20:06:15 2018

@author: eric
"""

from django.urls import path, re_path

from . import views

# app_name is a namespace varaible
app_name = 'inputs'
urlpatterns = [
    path('', views.index, name='index'),

    path('broker_form/', views.broker_form, name='broker_form'),
    path('broker_list/', views.broker_list, name='broker_list'),

    re_path('lender/(?P<pk>[0-9]+)/$', views.lender_detail, name='lender_detail'),
    re_path('lender_form/(?P<pk>[0-9]+)/$', views.edit_lender_form, name='edit_lender_form'),
    path('lender_form/', views.lender_form, name='lender_form'),
    path('lender_list/', views.lender_list, name='lender_list'),

    re_path('loan/(?P<pk>[0-9]+)/$', views.loan_detail, name='loan_detail'),
    re_path('loan_form/(?P<pk>[0-9]+)/$', views.edit_loan_form, name='edit_loan_form'),
    path('loan_form/', views.loan_form, name='loan_form'),
    path('loan_list/', views.loan_list, name='loan_list'),

    path('ajax/load_loantype_form/', views.load_loantype_form , name = 'load_loantype_form'),
]

broker1/inputs/models.py
from django.db import models

# Create your models here.
LOAN_PURPOSE = (
    ('purch',  'Purchase'),
    ('refi',   'Refinance'),
    ('refurb', 'Refurbish'),
)

class Broker(models.Model):
    first_name = models.CharField(max_length=50, default=None, blank=True, null=True)
    last_name  = models.CharField(max_length=50, default=None, blank=True, null=True)
    address    = models.CharField(max_length=50, default=None, blank=True, null=True)
    city       = models.CharField(max_length=50, default=None, blank=True, null=True)
    state      = models.CharField(max_length=50, default=None, blank=True, null=True)
    zip_code   = models.CharField(max_length=50, default=None, blank=True, null=True)
    work_email = models.EmailField(max_length=50, default=None, blank=True, null=True)
    home_email = models.EmailField(max_length=50, default=None, blank=True, null=True)
    work_phone = models.CharField(max_length=50, default=None, blank=True, null=True)
    home_phone = models.CharField(max_length=50, default=None, blank=True, null=True)

class Loan(models.Model):

    # Boolean Choices
    YES = 'Yes'
    NO  = 'No'
    BOOLEAN_CHOICES = (
            (YES, 'Yes'),
            (NO,  'No'),
            )

    # Loan Type Choices
    OO = 'Owner Occupied'
    INV = 'Investment'
    CON = 'Construction'
    SBA = 'SBA'

    LOAN_TYPE_CHOICES = (
        ('None', 'Please Select'),
        ('Bloc', 'Bloc'),
        ('Construction', 'Construction'),
        ('Mixed Use', 'Mixed Use'),
        ('Multi Family', 'Multi Family'),
        ('Retail', 'Retail'),
            #(OO, 'Owner Occupied'),
            #(INV, 'Investment'),
            #(CON, 'Construction'),
            #(SBA, 'SBA'),
    )


    # Client Personal Information
    client_first_name     = models.CharField(max_length=200, default = None, blank = True, null = True)
    client_last_name      = models.CharField(max_length=200, default = None, blank = True, null = True)
    client_street_address = models.CharField(max_length=200, default = None, null = True)
    client_city           = models.CharField(max_length=200, default = None, blank = True, null = True)
    client_state          = models.CharField(max_length=200, default = None, blank = True, null = True)
    client_zip_code       = models.IntegerField(default = None, null = True)
    client_work_email     = models.EmailField(max_length=200, default = None, blank = True, null = True)
    client_personal_email = models.EmailField(max_length=200, default = None, blank = True, null = True)
    client_work_phone     = models.IntegerField(default = None, blank = True, null = True)
    client_cell_phone     = models.IntegerField(default = None, blank = True, null = True)
    client_using_poc      = models.CharField(max_length=3, choices=BOOLEAN_CHOICES, default=NO, )
    client_loan_type      = models.CharField(max_length=15, choices=LOAN_TYPE_CHOICES, default=None)

    # POC Contact Information
    POC_name              = models.CharField(max_length=200, default = None, blank = True, null = True)
    POC_business          = models.CharField(max_length=200, default = None, blank = True, null = True)
    POC_work_phone        = models.IntegerField(default = None, blank = True, null = True)
    POC_cell_phone        = models.IntegerField(default = None, blank = True, null = True)
    POC_email             = models.EmailField(max_length=200, default = None, blank = True, null = True)

    # Client occupation and company information
    client_occupation             = models.CharField(max_length=200, default = None, blank = True, null = True)
    client_company_name           = models.CharField(max_length=200, default = None, blank = True, null = True)
    client_company_street_address = models.CharField(max_length=200, default = None, blank = True, null = True)
    client_company_city           = models.CharField(max_length=200, default = None, blank = True, null = True)
    client_company_state          = models.CharField(max_length=200, default = None, blank = True, null = True)
    client_company_zip            = models.IntegerField(default = None, blank = True, null = True)

    # Loan Information
    loan_amount   = models.IntegerField(default = None, blank = True, null = True)
    loan_to_value = models.IntegerField(default = None, blank = True, null = True)
    loan_dcsr     = models.IntegerField(default = None, blank = True, null = True)
    loan_desc     = models.CharField(max_length=200, default = None, blank = True, null = True)

    # Financial Information
    fin_salary            = models.IntegerField(default = None, blank = True, null = True)
    fin_years_in_business = models.IntegerField(default = None, blank = True, null = True)
    fin_total_debt        = models.IntegerField(default = None, blank = True, null = True)
    fin_monthly_payments  = models.IntegerField(default = None, blank = True, null = True)
    fin_fico              = models.IntegerField(default = None, blank = True, null = True)
    fin_owns_home         = models.BooleanField()
    fin_bankruptcy        = models.BooleanField()
    fin_short_sale        = models.BooleanField()

    # Property Information
    property_address = models.CharField(max_length=200, default = None, blank = True, null = True)
    property_value   = models.IntegerField(default = None, blank = True, null = True)

    # Docs (Needs List)
    docs_executive_summary = models.BooleanField()
    docs_credit_report     = models.BooleanField()
    docs_personal_taxes    = models.BooleanField()
    docs_business_taxes    = models.BooleanField()
    docs_P_and_L           = models.BooleanField()
    docs_expense_report    = models.BooleanField()
    docs_brokers_opinion   = models.BooleanField()
    docs_appraisal         = models.BooleanField()
    docs_environmental     = models.BooleanField()
    docs_rent_roll         = models.BooleanField()
    docs_lease_agreements  = models.BooleanField()

    # Commercial Business Information
    business_name             = models.CharField(max_length=200, default = None, blank = True, null = True)
    business_main_phone       = models.CharField(max_length=200, default = None, blank = True, null = True)
    business_website          = models.CharField(max_length=200, default = None, blank = True, null = True)
    business_type             = models.CharField(max_length=200, default = None, blank = True, null = True)
    business_year_established = models.IntegerField(default = None, blank = True, null = True)



    def __str__(self):
        return "{} {}".format(self.client_first_name, self.client_last_name)

# Create your models here.
class Lender(models.Model):

    YES = 'Yes'
    NO  = 'No'
    UNK = 'Unk'

    BOOLEAN_CHOICES = (
            (YES, 'Yes'),
            (NO,  'No'),
            )
            #(UNK, 'Unk'),

    # Lender Personal Information
    lender_first_name     = models.CharField(max_length=200, default = None, blank = True, null = True)
    lender_last_name      = models.CharField(max_length=200, default = None, blank = True, null = True)
    lender_company        = models.CharField(max_length=200, default = None, blank = True, null = True)
    lender_street_address = models.CharField(max_length=200, default = None, null = True)
    lender_city           = models.CharField(max_length=200, default = None, blank = True, null = True)
    lender_state          = models.CharField(max_length=200, default = None, blank = True, null = True)
    lender_zip_code       = models.IntegerField(default = None, null = True)
    lender_work_email     = models.EmailField(max_length=200, default = None, blank = True, null = True)
    lender_personal_email = models.EmailField(max_length=200, default = None, blank = True, null = True)
    lender_work_phone     = models.IntegerField(default = None, blank = True, null = True)
    lender_cell_phone     = models.IntegerField(default = None, blank = True, null = True)
    lender_solicitation   = models.IntegerField(default = None, blank = True, null = True)

    # Owner Occupied
    oo_office        = models.BooleanField()
    oo_warehouse     = models.BooleanField()
    oo_manufacturing = models.BooleanField()
    oo_medical       = models.BooleanField()
    oo_mixed_use     = models.BooleanField()
    oo_other         = models.BooleanField()

    # Investment
    inv_office        = models.BooleanField()
    inv_warehouse     = models.BooleanField()
    inv_manufacturing = models.BooleanField()
    inv_medical       = models.BooleanField()
    inv_mixed_use     = models.BooleanField()
    inv_other         = models.BooleanField()

    # Multifamily
    mf_2to4 = models.BooleanField()
    mf_gt4  = models.BooleanField()

    # Construction
    constr_renovation     = models.BooleanField()
    constr_ground_up_spec = models.BooleanField()
    constr_commercial     = models.BooleanField()
    constr_residential    = models.BooleanField()
    constr_inv_with_land  = models.BooleanField()
    constr_oo_with_land   = models.BooleanField()

    # SBA
    sba_7a      = models.BooleanField()
    sba_504     = models.BooleanField()
    sba_CAPline = models.BooleanField()
    sba_micro   = models.BooleanField()
    sba_other   = models.BooleanField()

    # HELOC
    heloc_1_pos = models.BooleanField()
    heloc_2_pos = models.BooleanField()

    # BLOC
    bloc_resid_prop = models.BooleanField()
    bloc_stocks     = models.BooleanField()
    bloc_savings    = models.BooleanField()
    bloc_inv_prop   = models.BooleanField()
    bloc_1_pos      = models.BooleanField()
    bloc_2_pos      = models.BooleanField()

    # Bridge
    bridge          = models.BooleanField()

    # Qualifiers
    qual_pays_fees        = models.BooleanField()
    qual_outside_ca       = models.BooleanField()
    qual_1031_exchange    = models.BooleanField()
    qual_lt_500K          = models.BooleanField()
    qual_lt_1M            = models.BooleanField()

broker1/inputs/templates/inputs/broker_form.html
{% extends 'inputs/base.html' %}
{% block content %}
    <h1>Broker Form</h1>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    {% if lender.id %}
    <form name="form" action="{% url 'inputs:edit_lender_form' pk=lender.id %}" method="POST">
    {% else %}
    <form name="form" action="{% url 'inputs:broker_form' %}" method="POST">
    {% endif %}
      {% csrf_token %}

      <!-- Name Table -->
      <div class="formContainer">
        <div class="grid3c">
          <h1 class="formHeader">Broker Information</h1>
          <label>First Name:</label>
          {{ form.first_name }}
          <label>Last Name:</label>
          {{ form.last_name }}
          <label>Address:</label>
          {{ form.address }}
          <label>City:</label>
          {{ form.city }}
          <label>State:</label>
          {{ form.state }}
          <label>Zip:</label>
          {{ form.zip_code }}
          <label>Email:</label>
          {{ form.home_email }}
          <label>Work Email:</label>
          {{ form.work_email }}
          <label>Cell Phone:</label>
          {{ form.home_phone }}
          <label>Work Phone:</label>
          {{ form.work_phone }}
        </div>
      </div>

      <center>
        <button>{{ submit }}</button>
      </center>
    </form>
{% endblock %}

broker1/inputs/templates/inputs/broker_list.html
{% extends 'inputs/base.html' %}
{% load static %}
{% block content %}
    <section class="container">
      <header>
        Broker Information
        <button type="button" class="btn btn-broker btn-xs pull-right">
          <a href="{% url 'inputs:broker_form' %}">
            <span class="glyphicon glyphicon-plus-sign"></span> Add Broker
          </a>
        </button>
      </header>
      <section class="content">
        <table class="table table-striped table-hover">
          <thead>
            <tr>
              <th>First Name</th>
              <th>Last Name</th>
              <th>Work Email</th>
              <th>Work Phone</th>
            </tr>
          </thead>
          {% for broker in brokers %}
          <tr><!-- class="row-link" data-href="/inputs/broker_form/{{ broker.id }}/"-->
            <td>{{ broker.first_name }}</td>
            <td>{{ broker.last_name }}</td>
            <td>{{ broker.work_email }}</td>
            <td>{{ broker.work_phone }}</td>
          </tr>
          {% empty %}
          <tr>
            <td align="center" colspan="4">No Brokers to display</td>
          </tr>
          {% endfor %}
        </table>
      </section>
    </section>

    <script type="text/javascript" src="{% static 'inputs/js/list.js' %}"></script>
{% endblock %}

broker1/inputs/templates/inputs/index.html
{% extends 'inputs/base.html' %}

broker1/inputs/templates/inputs/lender_list.html
{% extends 'inputs/base.html' %}
{% load static %}
{% block content %}
    <section class="container">
      <header>
        Lender Information
        <button type="button" class="btn btn-broker btn-xs pull-right">
          <a href="{% url 'inputs:lender_form' %}">
            <span class="glyphicon glyphicon-plus-sign"></span> Add Lender
          </a>
        </button>
      </header>
      <section class="content">
        <table class="table table-striped table-hover">
          <thead>
            <tr>
              <th>First Name</th>
              <th>Last Name</th>
              <th>Company</th>
            </tr>
          </thead>
          {% for lender in lenders %}
          <tr class="row-link" data-href="/inputs/lender_form/{{ lender.id }}">
            <td>{{ lender.lender_first_name }}</td>
            <td>{{ lender.lender_last_name }}</td>
            <td>{{ lender.lender_company }}</td>
          </tr>
          {% empty %}
          <tr>
            <td align="center" colspan="3">No Lenders to display</td>
          </tr>
          {% endfor %}
        </table>
      </section>
    </section>

    <script type="text/javascript" src="{% static 'inputs/js/list.js' %}"></script>
{% endblock %}

broker1/inputs/templates/inputs/loan_detail.html
{% extends 'inputs/base.html' %}
{% block content %}
    <h1>Loan Form</h1>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    <form name="form" action="{% url 'inputs:edit_loan_form' pk=loan_data.id %}" method="GET">
    {% csrf_token %}

      <!-- Personal Information Table -->
      <div class="formContainer">
        <div class="grid3c">
          <h1 class="formHeader">Personal Information</h1>
          <label>First Name:</label>
          {{ loan_data.client_first_name }}
          <label>Last Name:</label>
          {{ loan_data.client_last_name }}
          <label>Email:</label>
          {{ loan_data.client_personal_email }}
          <label>Work Email:</label>
          {{ loan_data.client_work_email }}
          <label>Address:</label>
          {{ loan_data.client_street_address }}
          <label>City:</label>
          {{ loan_data.client_city }}
          <label>State:</label>
          {{ loan_data.client_state }}
          <label>Zip:</label>
          {{ loan_data.client_zip_code }}
          <label>Cell Phone:</label>
          {{ loan_data.client_cell_phone }}
          <label>Work Phone:</label>
          {{ loan_data.client_work_phone }}
          <label>Using POC:</label>
          {{ loan_data.client_using_poc }}
          <label>Loan Type:</label>
          {{ loan_data.client_loan_type.label_tag }}
          {{ loan_data.client_loan_type }}
        </div>
      </div>

      <div id="loanTypeForm">
      {% if loantype != 'None' and loantype is not None%}
        <div class="formContainer">
          <div class="grid3c">
            <h1 class="formHeader">{{ loantype }}</h1>
            {% for field in loantype_fields %}
                {{ field.label_tag }}
                {{ field.value }}
            {% endfor %}
          </div>
        </div>
      {% endif %}
      </div>

<!-- POC Information Table -->
      <div class="formContainer">
        <div class="grid3c">
          <h1 class="formHeader">Client POC Information</h1>
          <label>POC Name:</label>
          {{ loan_data.POC_name }}
          <label>POC Company:</label>
          {{ loan_data.POC_business }}
          <label>POC Work Phone:</label>
          {{ loan_data.POC_work_phone }}
          <label>POC Cell Phone:</label>
          {{ loan_data.POC_cell_phone }}
          <label>POC Email:</label>
          {{ loan_data.POC_email }}
        </div>
      </div>

      <!-- Business Table -->
      <div class="formContainer">
        <div class="grid3c">
          <h1 class="formHeader">Client Business Information</h1>
          <label>Occupation:</label>
          {{ loan_data.client_occupation }}
          <label>Company Name:</label>
          {{ loan_data.client_company_name }}
          <label>Address:</label>
          {{ loan_data.client_company_street_address }}
          <label>City:</label>
          {{ loan_data.client_company_city }}
          <label>State:</label>
          {{ loan_data.client_company_state }}
          <label>Zip:</label>
          {{ loan_data.client_company_zip }}
        </div>
      </div>

      <!-- Loan Table -->
      <div class="formContainer">
        <div class="grid3c">
          <h1 class="formHeader">Loan Information</h1>
          <label>Loan Amount:</label>
          {{ loan_data.loan_amount }}
          <label>Loan To Value:</label>
          {{ loan_data.loan_to_value }}
          <label>Loan DSCR:</label>
          {{ loan_data.loan_dcsr }}
          <label>Loan Description:</label>
          {{ loan_data.loan_desc }}
        </div>
      </div>

      <!-- Financial Table -->
      <div class="formContainer">
        <div class="grid3c">
          <h1 class="formHeader">Client Financial Information</h1>
          <label>Salary:</label>
          {{ loan_data.fin_salary }}
          <label>Years in Business:</label>
          {{ loan_data.fin_years_in_business }}
          <label>Total Debt:</label>
          {{ loan_data.fin_total_debt }}
          <label>Total Monthly Payments:</label>
          {{ loan_data.fin_monthly_payments }}
          <label>FICO:</label>
          {{ loan_data.fin_fico }}
          <label>Owns Home:</label>
          {{ loan_data.fin_owns_home }}
          <label>Bankruptcy?:</label>
          {{ loan_data.fin_bankruptcy }}
          <label>Short Sale:</label>
          {{ loan_data.fin_short_sale }}
        </div>
      </div>

      <!-- Property Information -->
      <div class="formContainer">
        <div class="grid2c">
          <h1 class="formHeader">Property Information (Obtained)</h1>
          <label>Property Address:</label>
          {{ loan_data.property_address }}
          <label>Property Value:</label>
          {{ loan_data.property_value }}
        </div>
      </div>

      <!-- Needs List -->
      <div class="formContainer">
        <div class="grid3c">
          <h1 class="formHeader">Needs List</h1>
          <label>Executive Summary:</label>
          {{ loan_data.docs_executive_summary }}
          <label>Credit Report:</label>
          {{ loan_data.docs_credit_report }}
          <label>Personal Taxes:</label>
          {{ loan_data.docs_personal_taxes }}
          <label>Business Taxes:</label>
          {{ loan_data.docs_business_taxes }}
          <label>P & L:</label>
          {{ loan_data.docs_P_and_L }}
          <label>Expense Report:</label>
          {{ loan_data.docs_expense_report }}
          <label>Broker's Opinion:</label>
          {{ loan_data.docs_brokers_opinion }}
          <label>Appraisal:</label>
          {{ loan_data.docs_appraisal }}
          <label>Environmental:</label>
          {{ loan_data.docs_environmental }}
          <label>Rent Roll:</label>
          {{ loan_data.docs_rent_roll }}
          <label>Lease Agreements:</label>
          {{ loan_data.docs_lease_agreements }}
        </div>
      </div>

      <!-- Needs List -->
      <div class="formContainer">
        <div class="grid3c">
          <h1 class="formHeader">Business Info</h1>
          <label>Business Name:</label>
          {{ loan_data.business_name }}
          <label>Business Main Phone:</label>
          {{ loan_data.business_main_phone }}
          <label>Business Website:</label>
          {{ loan_data.business_website }}
          <label>Business Type:</label>
          {{ loan_data.business_type }}
          <label>Year Established:</label>
          {{ loan_data.business_year_established }}
        </div>
      </div>

      <center>
        <button>Edit</button>
      </center>
    </form>
{% endblock %}

broker1/inputs/templates/inputs/loan_form.html
{% extends 'inputs/base.html' %}
{% block content %}
    <h1>Loan Form</h1>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    {% if loan_id %}
    <form name="form" action="{% url 'inputs:edit_loan_form' pk=loan_id %}" method="POST">
    {% else %}
    <form name="form" action="{% url 'inputs:loan_form' %}" method="POST">
    {% endif %}
    {% csrf_token %}

    <!-- Personal Information Table -->
    <div class="formContainer">
      <div class="grid3c">
        <h1 class="formHeader">Personal Information</h1>
        <label>First Name:</label>
        {{ form.client_first_name }}
        <label>Last Name:</label>
        {{ form.client_last_name }}
        <label>Email:</label>
        {{ form.client_personal_email }}
        <label>Work Email:</label>
        {{ form.client_work_email }}
        <label>Address:</label>
        {{ form.client_street_address }}
        <label>City:</label>
        {{ form.client_city }}
        <label>State:</label>
        {{ form.client_state }}
        <label>Zip:</label>
        {{ form.client_zip_code }}
        <label>Cell Phone:</label>
        {{ form.client_cell_phone }}
        <label>Work Phone:</label>
        {{ form.client_work_phone }}
        <label>Using POC:</label>
        <label>
        {% for choice in form.client_using_poc %}
          <label>{{ choice }}&nbsp;&nbsp;&nbsp;&nbsp;</label>
        {% endfor %}
        </label>
        <label>Loan Type:</label>
        {{ form.client_loan_type }}
      </div>
    </div>

    <!-- space reserved for selected loan type -->
    {% if loantype is not None and loantype != 'None' %}
    <div id="loanTypeForm">
      <div class="formContainer">
        <div class="grid3c">
          <h1 class="formHeader">{{ loantype }}</h1>
          {% for field in loantype_fields %}
              {{ field.label_tag }}
              {{ field }}
          {% endfor %}
        </div>
      </div>
    </div>
    {% else %}
    <div id="loanTypeForm" style="display: none;">
    </div>
    {% endif %}

<!-- POC Information Table -->
    <div class="formContainer">
      <div class="grid3c">
        <h1 class="formHeader">Client POC Information</h1>
        <label>POC Name:</label>
        {{ form.POC_name }}
        <label>POC Company:</label>
        {{ form.POC_business }}
        <label>POC Work Phone:</label>
        {{ form.POC_work_phone }}
        <label>POC Cell Phone:</label>
        {{ form.POC_cell_phone }}
        <label>POC Email:</label>
        {{ form.POC_email }}
      </div>
    </div>

    <!-- Business Table -->
    <div class="formContainer">
      <div class="grid3c">
        <h1 class="formHeader">Client Business Information</h1>
        <label>Occupation:</label>
        {{ form.client_occupation }}
        <label>Company Name:</label>
        {{ form.client_company_name }}
        <label>Address:</label>
        {{ form.client_company_street_address }}
        <label>City:</label>
        {{ form.client_company_city }}
        <label>State:</label>
        {{ form.client_company_state }}
        <label>Zip:</label>
        {{ form.client_company_zip }}
      </div>
    </div>

    <!-- Loan Table -->
    <div class="formContainer">
      <div class="grid3c">
        <h1 class="formHeader">Loan Information</h1>
        <label>Loan Amount:</label>
        {{ form.loan_amount }}
        <label>Loan To Value:</label>
        {{ form.loan_to_value }}
        <label>Loan DSCR:</label>
        {{ form.loan_dcsr }}
        <label>Loan Description:</label>
        {{ form.loan_desc }}
      </div>
    </div>

    <!-- Financial Table -->
    <div class="formContainer">
      <div class="grid3c">
        <h1 class="formHeader">Client Financial Information</h1>
        <label>Salary:</label>
        {{ form.fin_salary }}
        <label>Years in Business:</label>
        {{ form.fin_years_in_business }}
        <label>Total Debt:</label>
        {{ form.fin_total_debt }}
        <label>Total Monthly Payments:</label>
        {{ form.fin_monthly_payments }}
        <label>FICO:</label>
        {{ form.fin_fico }}
        <label>Owns Home:</label>
        <label>{{ form.fin_owns_home }}</label>
        <label>Bankruptcy?:</label>
        <label>{{ form.fin_bankruptcy }}</label>
        <label>Short Sale:</label>
        <label>{{ form.fin_short_sale }}</label>
      </div>
    </div>

    <!-- Property Information -->
    <div class="formContainer">
      <div class="grid2c">
        <h1 class="formHeader">Property Information (Obtained)</h1>
        <label>Property Address:</label>
        {{ form.property_address }}
        <label>Property Value:</label>
        {{ form.property_value }}
      </div>
    </div>

    <!-- Needs List -->
    <div class="formContainer">
      <div class="grid3c">
        <h1 class="formHeader">Needs List</h1>
        <label>Executive Summary:</label>
        <label>{{ form.docs_executive_summary }}</label>
        <label>Credit Report:</label>
        <label>{{ form.docs_credit_report }}</label>
        <label>Personal Taxes:</label>
        <label>{{ form.docs_personal_taxes }}</label>
        <label>Business Taxes:</label>
        <label>{{ form.docs_business_taxes }}</label>
        <label>P &amp; L:</label>
        <label>{{ form.docs_P_and_L }}</label>
        <label>Expense Report:</label>
        <label>{{ form.docs_expense_report }}</label>
        <label>Broker's Opinion:</label>
        <label>{{ form.docs_brokers_opinion }}</label>
        <label>Appraisal:</label>
        <label>{{ form.docs_appraisal }}</label>
        <label>Environmental:</label>
        <label>{{ form.docs_environmental }}</label>
        <label>Rent Roll:</label>
        <label>{{ form.docs_rent_roll }}</label>
        <label>Lease Agreements:</label>
        <label>{{ form.docs_lease_agreements }}</label>
      </div>
    </div>

    <!-- Needs List -->
    <div class="formContainer">
      <div class="grid3c">
        <h1 class="formHeader">Business Info</h1>
        <label>Business Name:</label>
        {{ form.business_name }}
        <label>Business Main Phone:</label>
        {{ form.business_main_phone }}
        <label>Business Website:</label>
        {{ form.business_website }}
        <label>Business Type:</label>
        {{ form.business_type }}
        <label>Year Established:</label>
        {{ form.business_year_established }}
      </div>
    </div>

    <center>
      <button>{{ submit }}</button>
    </center>
    </form>
    <script>
    // TODO: put jquery in separate file
    $('#id_client_loan_type').change(function() {
        var choice = $('#id_client_loan_type').val();
        if (choice == 'None') {
            $("#loanTypeForm").slideUp();
            $("#loanTypeForm").empty();
        } else {
            var url = "/inputs/ajax/load_loantype_form/";
            $.ajax({
                url: url,
                data: {
                    'loantype': choice
                },
                success: function (data) {
                    $("#loanTypeForm").html(data);
                    $("#loanTypeForm").slideDown();
                }
            });
        }
    });
    </script>
{% endblock %}